import React from "react";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import dynamic from "next/dynamic";
import SubscribeModal from "./components/SubscribeModal/SubscribeModal";
import { BootstrapLoader } from "./components/BootstrapLink/BootstrapLink";
import { LinkMenuProvider } from "./public/context/context";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
  display: "swap", // Optimize font loading
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const CookieModal = dynamic(
  () => import("./components/CookieModal/CookieModal"),
  {
    ssr: false,
  }
);

// Dynamically load Footer with a loading placeholder
const Footer = dynamic(() => import("./components/Footer/Footer"), {
  loading: () => <h1>Loading...</h1>,
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>{/* <BootstrapLoader /> */}</head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <LinkMenuProvider>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              minHeight: "100vh",
            }}>
            <nav>
              <Navbar />
            </nav>
            <main style={{ flexGrow: 1, padding: "20px" }}>{children}</main>
            {/* Dynamically load CookieModal */}
            <CookieModal />
            <SubscribeModal />
            <div>
              <Footer />
            </div>
          </div>
        </LinkMenuProvider>
      </body>
    </html>
  );
}
